Add french translation file
quek04/The-Undergarden pull request #196
Opened 2024-08-16 19:23 UTC by Arona74

Hi, just made a french lang file for last 1.21 version.

2024-08-25 20:39 UTC, Fooshcookie commented
I'll check with the big man.

2025-02-11 02:42 UTC, elliotfontaine commented
Très très fan des traductions que tu as proposé @Arona74 🤩

Pour **Gwib** et **Gwibling**, est-ce qu'on pourrait pas trouver un nom bizarre, plutôt que Silure Albinos qui évoque un animal réel ?
- Siluvore
- Abyssure
- Pâluron

Et pour **Rotbeast**, **Rotling**, **Rotwalker**, plutôt que "pourri" j'ai pensé aux adjectifs suivants:
- putride
- putréfié
- charogné

J'espère que ce PR finira par être mergé!

2025-02-11 07:18 UTC, Arona74 commented
Merci du retour!L’auteur du mod utilise beaucoup de mots venant de l’argot anglais voir australien, très souvent connoté vulgaire. Par exemple le gwib: http://gwib.urbanup.com/2842520Donc faut choisir entre une traduction se voulant plus réelle ou connotée mais c’est jamais simple de trouver.Pour les « rots », j’hésitais entre pourri/pourriture et putréfié/putréfaction. 6 mois plus tard j’ai une préférence pour putréfié. Je pense que j’étais allé sur pourri pour le côté plus sale et connoté du mot.Le 11 févr. 2025 à 03:42, Elliot Fontaine ***@***.***> a écrit :﻿
Très très fan des traductions que tu as proposé @Arona74 🤩
Pour Gwib et Gwibling, est-ce qu'on pourrait pas trouver un nom bizarre, plutôt que Silure Albinos qui évoque un animal réel ?

Siluvore
Abyssure
Pâluron

Et pour Rotbeast, Rotling, Rotwalker, plutôt que "pourri" j'ai pensé aux adjectifs suivants:

putride
putréfié
charogné

J'espère que ce PR finira par être mergé!

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2025-02-12 18:02 UTC, elliotfontaine reviewed
EN: You missed some lines that are still in english.
FR: Tu as oublié de traduire quelques lignes.

2025-02-12 18:02 UTC, elliotfontaine commented on src/main/resources/assets/undergarden/lang/fr_fr.json
> +  "block.undergarden.chiseled_tremblecrust_bricks": "Chiseled Tremblecrust Bricks",
Not localized.

2025-02-12 18:02 UTC, elliotfontaine commented on src/main/resources/assets/undergarden/lang/fr_fr.json
> +  "block.undergarden.cracked_tremblecrust_bricks": "Cracked Tremblecrust Bricks",
Not localized.

2025-02-12 18:02 UTC, elliotfontaine commented on src/main/resources/assets/undergarden/lang/fr_fr.json
> +  "block.undergarden.tremblecrust": "Tremblecrust",
Not localized (from line 232 to 242).

2025-02-14 19:08 UTC, Arona74 commented
**EN**:
I updated the file:

Add Tremblecrust translation
Change Rot translation
Change Gwib and Gwibling translation
Minor typo changes

**FR**:
J'ai changé en Putréfaction/Putréfié, le silure est devenu Fripé et Fripette pour reprendre la définition d'origine et j'ai traduit Tremblecrust en Croûte.

2025-02-14 22:54 UTC, elliotfontaine requested changes
- Traduction des paramètres.
- `50% [...] supplémentaires` plutôt que `1.5x`
- `de l'Undergarden` plutôt que `d'Undergarden`

2025-02-14 22:54 UTC, elliotfontaine commented on src/main/resources/assets/undergarden/lang/fr_fr.json
> +  "advancement.undergarden.enter_undergarden.title": "Entrez dans le Jardin Souterrain",
```suggestion
  "advancement.undergarden.enter_undergarden.title": "Entrez dans l'Undergarden",
```

2025-02-14 22:54 UTC, elliotfontaine commented on src/main/resources/assets/undergarden/lang/fr_fr.json
> +  "advancement.undergarden.mine_ore.desc": "Acquérir n'importe quel minerai d'Undergarden.",
```suggestion
  "advancement.undergarden.mine_ore.desc": "Obtenir n'importe quel minerai de l'Undergarden.",
```

2025-02-14 22:54 UTC, elliotfontaine commented on src/main/resources/assets/undergarden/lang/fr_fr.json
> +  "block.undergarden.undergarden_portal": "Portail d'Undergarden",
```suggestion
  "block.undergarden.undergarden_portal": "Portail de l'Undergarden",
```

2025-02-14 22:54 UTC, elliotfontaine commented on src/main/resources/assets/undergarden/lang/fr_fr.json
> +  "tooltip.undergarden.forgotten_tool": "Mine les blocs d'Undergarden 1.5x plus vite.",
```suggestion
  "tooltip.undergarden.forgotten_tool": "Mine les blocs de l'Undergarden 50% plus vite.",
```

2025-02-14 22:54 UTC, elliotfontaine commented on src/main/resources/assets/undergarden/lang/fr_fr.json
> +  "tooltip.undergarden.forgotten_weapon": "Inflige 1.5x de dégâts aux entités d'Undergarden qui ne sont pas des boss.",
```suggestion
  "tooltip.undergarden.forgotten_weapon": "Inflige 50% de dégâts supplémentaires aux entités de l'Undergarden qui ne sont pas des boss.",
```

2025-02-14 22:54 UTC, elliotfontaine commented on src/main/resources/assets/undergarden/lang/fr_fr.json
> +  "config.undergarden.return_portal_frame_block_id": "Return Portal Frame Block ID",
```suggestion
  "config.undergarden.return_portal_frame_block_id": "ID de bloc pour le portail retour",
```

2025-02-14 22:54 UTC, elliotfontaine commented on src/main/resources/assets/undergarden/lang/fr_fr.json
> +  "config.undergarden.toggle_undergarden_fog": "Toggle Undergarden Fog",
```suggestion
  "config.undergarden.toggle_undergarden_fog": "Brouillard dans l'Undergarden",					
```

2025-02-14 22:54 UTC, elliotfontaine commented on src/main/resources/assets/undergarden/lang/fr_fr.json
> +  "tooltip.undergarden.utherium_weapon": "Inflige 1.5x de dégâts aux Engeances de la pourriture.",
```suggestion
  "tooltip.undergarden.utherium_weapon": "Inflige 50% de dégâts supplémentaires aux Engeances de la pourriture.",
```

2025-02-14 22:59 UTC, elliotfontaine commented on src/main/resources/assets/undergarden/lang/fr_fr.json
> +  "config.undergarden.return_portal_frame_block_id": "Return Portal Frame Block ID",
Mince j'ai fait mes suggestions sur le commit précédent au lieu du plus récent...

2025-02-15 00:05 UTC, Arona74 commented
EN:
Added elliotfontaine suggestions

FR:
J'ai ajouté tes suggestions.

2025-02-15 10:47 UTC, elliotfontaine commented
@quek04 Hi! This is ready to be merged. 👍

2025-06-19 05:04 UTC, merged